# Generated by Django 5.2.7 on 2025-10-12 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspectRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='宽高比（如 1:1、4:3、16:9）', max_length=20, unique=True)),
                ('ratio_w', models.PositiveIntegerField(help_text='宽比（分子，例如 16:9 的 16）')),
                ('ratio_h', models.PositiveIntegerField(help_text='高比（分母，例如 16:9 的 9）')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该宽高比')),
            ],
        ),
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='色彩名称', max_length=30, unique=True)),
                ('main_color', models.CharField(help_text='主色调HEX值', max_length=20)),
                ('preview_image', models.URLField(blank=True, help_text='色彩预览图片URL', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='排序值')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该色彩方案')),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='字体名称', max_length=50, unique=True)),
                ('category', models.CharField(blank=True, help_text='字体类别标签', max_length=30, null=True)),
                ('demo_image', models.URLField(blank=True, help_text='字体示例图片URL', null=True)),
                ('is_system', models.BooleanField(default=False, help_text='系统常用字体（前端常用推荐）')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该字体')),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='布局名称', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, help_text='布局描述', null=True)),
                ('layout_type', models.CharField(blank=True, help_text='布局类型标签', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该布局')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='尺寸规格（如 2K、2048x2048、1080x1920）', max_length=20, unique=True)),
                ('width', models.PositiveIntegerField(help_text='像素宽度')),
                ('height', models.PositiveIntegerField(help_text='像素高度')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该尺寸')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='场景名称', max_length=50, unique=True)),
                ('icon', models.URLField(blank=True, help_text='场景图标URL', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该场景')),
                ('tags', models.CharField(blank=True, help_text='用于场景分组和检索的标签，逗号分隔', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='poster_enum_is_acti_709b07_idx'), models.Index(fields=['name'], name='poster_enum_name_b6e261_idx')],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='风格名称', max_length=30, unique=True)),
                ('reference_images', models.JSONField(blank=True, default=list, help_text='风格参考图片URL列表（JSON 数组）')),
                ('tags', models.CharField(blank=True, help_text='风格标签，逗号分隔', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该风格')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='poster_enum_is_acti_4c107f_idx'), models.Index(fields=['name'], name='poster_enum_name_14645f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='图片名称', max_length=50)),
                ('image_url', models.URLField(help_text='图片URL')),
                ('tags', models.CharField(blank=True, help_text='图片标签分组', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该图片')),
                ('style', models.ForeignKey(blank=True, help_text='关联风格', null=True, on_delete=django.db.models.deletion.SET_NULL, to='poster_enums.style')),
            ],
        ),
        migrations.CreateModel(
            name='PosterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='海报类型名称', max_length=50, unique=True)),
                ('tags', models.CharField(blank=True, help_text='类型标签，逗号分隔（冷启动相似度用）', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='排序值')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活该类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('scene', models.ForeignKey(blank=True, help_text='主推荐关联场景（冷启动兜底用）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='poster_enums.scene')),
                ('scenes', models.ManyToManyField(blank=True, help_text='该类型关联的多个场景', related_name='poster_types', to='poster_enums.scene')),
                ('styles', models.ManyToManyField(blank=True, help_text='该类型可用的风格集合（用于过滤候选集）', related_name='poster_types', to='poster_enums.style')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['is_active'], name='poster_enum_is_acti_6f05c6_idx'), models.Index(fields=['order'], name='poster_enum_order_400cf7_idx'), models.Index(fields=['name'], name='poster_enum_name_0c6833_idx')],
            },
        ),
    ]
