# Generated by Django 5.2.7 on 2025-10-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_enums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='height',
        ),
        migrations.RemoveField(
            model_name='size',
            name='width',
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(help_text='尺寸规格', max_length=20, unique=True),
        ),
    ]
