# Generated by Django 5.2.7 on 2025-10-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_poster_count',
            field=models.IntegerField(default=10, verbose_name='免费海报生成次数'),
        ),
    ]
