# Generated by Django 5.2.7 on 2025-10-17 07:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('plan_type', models.CharField(choices=[('monthly', '月度会员'), ('quarterly', '季度会员'), ('yearly', '年度会员'), ('lifetime', '终身会员')], max_length=20, verbose_name='套餐类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('duration_days', models.IntegerField(verbose_name='有效期天数')),
                ('description', models.TextField(blank=True, verbose_name='套餐描述')),
                ('features', models.JSONField(default=list, verbose_name='套餐特性列表')),
                ('poster_quota', models.IntegerField(default=-1, verbose_name='海报生成配额(-1表示无限)')),
                ('max_image_size', models.CharField(default='4K', max_length=20, verbose_name='最大图片尺寸')),
                ('priority_generation', models.BooleanField(default=False, verbose_name='优先生成')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '会员套餐',
                'verbose_name_plural': '会员套餐',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=64, verbose_name='商户订单号')),
                ('trade_no', models.CharField(max_length=64, verbose_name='支付宝交易号')),
                ('callback_data', models.JSONField(verbose_name='回调数据')),
                ('processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '支付回调记录',
                'verbose_name_plural': '支付回调记录',
            },
        ),
        migrations.CreateModel(
            name='MembershipOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(max_length=64, unique=True, verbose_name='商户订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('expired', '已过期'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态')),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('balance', '余额支付')], max_length=20, verbose_name='支付方式')),
                ('trade_no', models.CharField(blank=True, max_length=64, verbose_name='支付宝交易号')),
                ('alipay_response', models.JSONField(blank=True, default=dict, verbose_name='支付宝响应数据')),
                ('expires_at', models.DateTimeField(verbose_name='订单过期时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membershipplan', verbose_name='会员套餐')),
            ],
            options={
                'verbose_name': '会员订单',
                'verbose_name_plural': '会员订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='会员是否有效')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('total_orders', models.IntegerField(default=0, verbose_name='总订单数')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='总消费金额')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membershipplan', verbose_name='当前套餐')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_info', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户会员信息',
                'verbose_name_plural': '用户会员信息',
            },
        ),
    ]
