# Generated by Django 5.2.7 on 2025-10-12 05:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poster_enums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('VIEW', 'View'), ('SELECT_TYPE', 'Select Type'), ('SELECT_STYLE', 'Select Style'), ('GENERATE', 'Generate'), ('DOWNLOAD', 'Download')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poster_enums.postertype')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poster_enums.scene')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poster_enums.style')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['scene'], name='analytics_p_scene_i_1c1e91_idx'), models.Index(fields=['poster_type'], name='analytics_p_poster__0dae81_idx'), models.Index(fields=['style'], name='analytics_p_style_i_42968b_idx'), models.Index(fields=['user'], name='analytics_p_user_id_5bc665_idx'), models.Index(fields=['created_at'], name='analytics_p_created_78a151_idx')],
            },
        ),
        migrations.CreateModel(
            name='SceneTypeStyleStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decayed_score', models.FloatField(default=0.0)),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('select_type_count', models.PositiveIntegerField(default=0)),
                ('select_style_count', models.PositiveIntegerField(default=0)),
                ('generate_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('poster_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_enums.postertype')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_enums.scene')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster_enums.style')),
            ],
            options={
                'indexes': [models.Index(fields=['scene', 'poster_type'], name='analytics_s_scene_i_51b4f5_idx'), models.Index(fields=['scene', 'style'], name='analytics_s_scene_i_31df85_idx'), models.Index(fields=['poster_type', 'style'], name='analytics_s_poster__60814a_idx'), models.Index(fields=['scene'], name='analytics_s_scene_i_c6ee92_idx')],
                'unique_together': {('scene', 'poster_type', 'style')},
            },
        ),
    ]
