# Generated by Django 5.2.7 on 2025-10-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('prompt', models.TextField(verbose_name='生成提示词')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='图片URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='海报图片')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '海报任务',
                'verbose_name_plural': '海报任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
